language: python

python:
  - 3.6
  - 3.7

services:
  - postgresql

install:
  - pip install peewee psycopg2-binary --quiet
  - apt-get install disorderfs
  - pip install .

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mkdir -vp /tmp/test
  - disorderfs --shuffle-dirents=yes . /tmp/test
  - cd /tmp/test

script:
  - python -m unittest --verbose --locals tests.TestFields

notifications:
  email:
    recipients: juancarlospaco@gmail.com
    on_success: change
    on_failure: always

cache:
  apt: true
  pip: true

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.7
